### PR TITLE
add ability to edit feature flags in the CMS

### PR DESCRIPTION
**Pull request by Ciuffi**
not editing:
image
editing:
image
no flags:
image

### CODE REVIEW

**Review by kozr — CHANGES_REQUESTED** [review]
Pressing edit -> sponsor enable -> save. Didn't update sponsor flag to be true on firebase.

**Comment by Ciuffi** [comment]
@kozr I can't seem to reproduce this

Which firebase project are you checking? dev or prod?

**Comment by luceliu** [comment]
@Ciuffi I toggled a flag and hit save, it didnt save, what am i doing wrong

**Comment by Ciuffi** [comment]
@luceliu why does it only work for me :(( 

Anything in the console ?

**Comment by luceliu** [comment]
nothing in console. also the website select buttons become hidden (but still work if you click where they are) when the console is open, even if it's opened in a new window lol

**Comment by Ciuffi** [comment]
Currently it works on both my PC and my Mac.. 

@luceliu do you have some time this week where I can come try debug it on your machine? 

HMU on slack if you’re able. 

@kozr you too. 

Thanks!

**Comment by Ciuffi** [comment]
@luceliu  @kozr 

So turns out it just doesn't work on chrome because I used a really weird way to connect the select to vue... It shouldn't have worked on Firefox either so honestly idk what was going on.

Anyway, it should work now! Please try it out and let me know.

**Review by AustinKobayashi — APPROVED** [review]
works on chrome now

**Review by luceliu — APPROVED** [review]
nice!

**Pull request merged**
