### PR TITLE
added a bug

### PR DESCRIPTION
**Pull request by kozr**
Hello, I need help fixing this bug. Essentially, you are able to select more than 1 radio box. I've been trying to fix it for 3 hours with no luck. Please help.

### CODE REVIEW

**Review by ianmah — CHANGES_REQUESTED** [review]
fixed the bug but I don't think it will populate in db properly, you can have fun with that

**Comment by Ciuffi** [comment]
Should be fixed now, give it a try @ianmah @kozr

**Review by Ciuffi — APPROVED** [review]
feexed it

**Comment by Ciuffi** [comment]
btw I fixed it by adding a name attribute to the input fields. This puts them in a group together and only allows one to be active at a time (I'm using the key variable from the v-for above the input v-for as the name for the inputs.

**Review by ianmah — COMMENTED** [review]
I tried to upload an image but now it says
image


 Is this because I'm on dev environment or will this be a problem?

**Comment by Ciuffi** [comment]
@ianmah seemed to be a bug with the upload logic. If a image failed to upload, it was still creating the db entry.. I should have fixed this now but I was never able to get a failed upload.

Could you try to reproduce this? If you can't I think I fixed it.

**Comment by ianmah** [comment]
I am failing to upload with any image I try. Is anything in this repo's .env file different?

**Comment by Ciuffi** [comment]
Thats strange, it works for me. What happens when you try?

**Comment by ianmah** [comment]
I get the Failed to upload alert you just added

**Comment by Ciuffi** [comment]
I think all errors are console logged right now, could you check the console?

**Review by ianmah — APPROVED** [review]
Works now

**Pull request merged**
